# Generated by Django 3.0.5 on 2020-04-21 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('publish', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Family')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Store')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subcategory')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
