# Generated by Django 3.0.5 on 2020-04-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sales_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='code',
        ),
    ]
