# Generated by Django 3.0.5 on 2020-04-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200421_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='moq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
