# Generated by Django 3.0.5 on 2020-04-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sales_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Family',
        ),
    ]
