# Generated by Django 3.0.5 on 2020-04-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200424_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyitemsavg',
            old_name='week',
            new_name='salesweek',
        ),
    ]
