# Generated by Django 3.0.5 on 2020-04-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200424_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyItemsData',
        ),
    ]
