# Generated by Django 3.0.5 on 2020-04-25 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_weeklyitemsavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyItemsAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.FloatField()),
                ('ratio', models.FloatField()),
                ('mon', models.FloatField()),
                ('tue', models.FloatField()),
                ('wed', models.FloatField()),
                ('thur', models.FloatField()),
                ('fri', models.FloatField()),
                ('sat', models.FloatField()),
                ('sun', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
                ('salesweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeeklySales')),
            ],
            options={
                'verbose_name': 'Item Weekly Avg',
                'verbose_name_plural': 'Item Weekly Avg',
            },
        ),
    ]
