# Generated by Django 3.0.5 on 2020-04-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_weeklyitemsavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate_day', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('salesweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeeklySales')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrederItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.FloatField()),
                ('on_hand_quanty', models.FloatField()),
                ('order_quantity', models.FloatField()),
                ('moq', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WeeklyItemsAvg')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
