# Generated by Django 3.0.5 on 2020-04-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_orederitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orederitem',
            old_name='Order',
            new_name='order',
        ),
    ]
