# Generated by Django 3.0.5 on 2020-04-28 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200428_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='weeklysales',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
