# Generated by Django 3.0.5 on 2020-04-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200428_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='moq',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
