# Generated by Django 3.0.5 on 2020-04-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200429_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
