# Generated by Django 3.0.5 on 2020-04-30 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_sales_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyitemsavg',
            old_name='thur',
            new_name='thu',
        ),
        migrations.RenameField(
            model_name='weeklysales',
            old_name='thur',
            new_name='thu',
        ),
    ]
