# Generated by Django 3.0.5 on 2020-05-12 15:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200504_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(blank=True, choices=[('mm', 'Millimeter'), ('cm', 'Centimeters'), ('m', 'Meter'), ('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilograms'), ('mel', 'Milliliter'), ('l', 'Liter'), ('q', 'Quantity')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Prediction', 'Prediction'), ('Custom', 'Custom')], default='Prediction', max_length=255),
        ),
        migrations.AddField(
            model_name='salescharts',
            name='chart5',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salescharts',
            name='chart6',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
